spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/jewelryDb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.show-sql= true

spring.data.mongodb.uri=mongodb://localhost:27017/jewelryDb

security.jwt.secret-key=5c70271e0b9da99a3515e6ca8fa74e201b4da453aaada9c4e0460d0bc85c21596ebfa6c1936f396f67a18da70f92d76ebb11b9659b7a1993a575c38155b4bbc284e02a2541e32dfd0f2be92c3ab56e93205cd7e1473fa91219ce76329da4fd5ced12bdd0908af8e40dbb98f15166820fd098752e6196ab343a4ee14e32293580c47b586c203005a42b900dc318991a21db018eb02d3eda191880fa8230636e774625eed73d2d54e80ca6ef9d6ee8b08c4c0cb9faf6474f884f35cbcedf93d3713e0c3ea27b1c4e1ed33b1d87e1cc9ddf8a1300d097c204d4b01f7b1a9fdc599367acf3f816bbbc6b1da6ebd11655d5213594616abec398117ab949fee75a1365
security.jwt.expiration-time=3600000
security.jwt.refresh-token-expiration=604800000
spring.jpa.open-in-view=false
#
# Mail properties
spring.mail.host=smtp.yandex.ru
spring.mail.port=587
spring.mail.username=ivan.ziab@yandex.ru
spring.mail.password=pxhavqzjfbibnyyl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport=WARN